# Generated by Django 4.2.2 on 2023-08-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_categories_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='last',
            field=models.BooleanField(default=False),
        ),
    ]
